[package]
name = "ahc016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
fixedbitset = "=0.2.0"
# bitset-fixed = "=0.1.0"